export const FETCH_ALL = "FETCH_ALL";
export const CREATE = "CREATE";
export const UPDATE_INSTRUCTION = "UPDATE_INSTRUCTION";
export const ASSIGN_TOP = "ASSIGN_TOP";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const UPDATE_TOOLTIP_DESC = "UPDATE_TOOLTIP_DESC";
export const UPDATE_TOOLTIP_POS = "UPDATE_TOOLTIP_POS";
